### ISSUE TITLE
Predicted text is always same

### ISSUE THREAD

**Issue by skfaysal1997** [menon92/BangalASR#2]
Predicted text is always same for while inferencing

![Screenshot from 2021-10-06 18-30-52](https://user-images.githubusercontent.com/88619927/136202760-37bd45db-baa8-476d-9a04-b62198ab9ffa.png)

**Comment by menon92** [comment]
@skfaysal1997, Could you please share the notebook that you run for inference. 
I'm getting correct output by running [inference notebook](https://github.com/menon92/BangalASR/blob/main/notebooks/asr_inferance.ipynb)
Thanks

**Comment by MdFaysal97** [comment]
Sure!
[https://github.com/MdFaysal97/github-share/blob/main/inference.ipynb](url)

**Comment by skfaysal1997** [comment]
@menon92 Here's the inference notebook:
https://nbviewer.org/github/MdFaysal97/github-share/blob/main/inference.ipynb

**Comment by menon92** [comment]
@MdFaysal97 @skfaysal1997 Do you use the model that provided in this repository ? or you use your custom model ?

**Comment by MdFaysal97** [comment]
@menon92 Here's is the inference output of the model provided in the repo for my custom data.
[https://nbviewer.org/github/MdFaysal97/github-share/blob/main/asr_inferance.ipynb](url)
I thought the miss prediction make sense as you have already told it's a biased model. But when i tried training the model using your script i got the following error:
![list_error](https://user-images.githubusercontent.com/33193399/137253137-f7df498c-7fb0-48b6-a60f-1250a1bd26b6.png)

Anyway we can ignore the error by not passing the "_display_cb_" to the callbacks and complete the training.After training while i inference the model i got prediction like:
[https://github.com/menon92/BangalASR/issues/2#issue-1018226133](url)

**For your convenient,The scripts are:**
**_train.py_**
https://gist.github.com/MdFaysal97/34e1c03bbe8a2025cb7d2a185fe399fa
**_utils.py_**
https://gist.github.com/MdFaysal97/8c034076fd7d2467f13dbeaf1e1284db
**_config.py_**
https://gist.github.com/MdFaysal97/06bf4f1027baa167e1ba0b841d8962a6
**Can you please help?**

**Comment by rayat927** [comment]
I am also facing the same issue. I am using the model provided in this repo

**Comment by menon92** [comment]
@MdFaysal97 , @rayat927  The was a bug in training code. 
I did not pass the unique chars to VectorizeChar class, I update the code
```python
vectorizer = VectorizeChar(unique_chars, max_target_len)
```
Thanks
